env_vars:
  FLASK_APP: app.py
  FLASK_RUN_HOST: 0.0.0.0
  FLASK_RUN_PORT: "8080"

services:
  data-cache:
    type: redis
    attach_as: separate_variables
  svc-1:
    type: redis
    attach_as: url
