version: "3.9"
services:
   redis: 
     image: "redis:alpine"
     ports:
       - '6379:6379' 
   web:
     build: .
     ports:
       - "8000:5000"
     volumes:
       - .:/code
     environment:
       FLASK_DEBUG: "true"
     depends_on:
       - redis
